### ISSUE TITLE
How does NeuralHaircut overcome the "noisy orientations map" problem in real-world data?

### ISSUE THREAD

**Issue by 07hyx06** [SamsungLabs/NeuralHaircut#17]
Hi, thanks for your work and the code, the results are very impressive!

I'm new in the realm of hair reconstruction and modeling. I noticed in the Related Work Section the paper says:

> Non-uniform lighting and low effective resolution of the real-world data lead to orientation maps having excessive noise levels or lacking details.

How does NeuralHaircut solve this problem? 

In my understanding, the neural hair growth field may alleviate this problem to some extent, as it aggregates information across multi-views; thus, the noise may be reduced. In addition, the use of the prior model would also alleviate this problem as it constrains the resulting hair model to be within a valid space. 

What about your opinion? Thanks in advance.

**Comment by Vanessik** [comment]
Hi @07hyx06!  You are right! 

Orientations obtained using Gabor filters are very noisy and undirected.  Furthermore, 2D orientation maps provide only information on how hair looks on the surface and have no idea of how hair behaves inside the volume. 
To deal with this problem, we use diffusion-based prior that was trained on synthetic hairstyles. This way, we could produce realistic hair geometry inside the volume as well as resolve the problem with proper orientations.

Ideally, having a large dataset with synthetic 3D strand-based hairstyles could resolve all problems. Unfortunately, today there are just several publicly available datasets with very simple hairstyles, that сomplicates the reconstruction of highly curly hair.

**Comment by 07hyx06** [comment]
Got it, thanks!
