### ISSUE TITLE
Error testing the example provided

### ISSUE THREAD

**Issue by carlosedubarreto** [SamsungLabs/NeuralHaircut#4]
Hello, I'm trying to test using the provided that, but it returns with the following error

`index 66 is out of bounds for axis 0 with size 66`

I'm trying to debug but somthing is strange and I cant understadwhat is.
Can someone give me a help? thanks
![image](https://github.com/SamsungLabs/NeuralHaircut/assets/4061130/6fb479ce-ea2b-440e-a5bc-78a518cb8e5f)

**Comment by carlosedubarreto** [comment]
I think I've foud the problem, the values ar duplicating
![image](https://github.com/SamsungLabs/NeuralHaircut/assets/4061130/ac7ea79f-34c2-47d6-8586-e8fe079a7695)

Now I'll try to find why ☺️

**Comment by carlosedubarreto** [comment]
Found a solution changin a bit the information where it loads the images

        # self.images_lis = sorted(glob_imgs(os.path.join(self.data_dir, 'image')))
        self.images_lis = sorted(glob(os.path.join(self.data_dir, 'image','*.png')))

        # self.masks_lis = sorted(glob_imgs(os.path.join(self.data_dir, 'mask')))
        self.masks_lis = sorted(glob(os.path.join(self.data_dir, 'mask','*.png')))
#        load hair mask
        # self.hair_masks_lis = sorted(glob_imgs(os.path.join(self.data_dir, 'hair_mask')))
        self.hair_masks_lis = sorted(glob(os.path.join(self.data_dir, 'hair_mask','*.png')))
#             load orientations
        # self.orientations_lis = sorted(glob_imgs(os.path.join(self.data_dir, 'orientation_maps')))
        self.orientations_lis = sorted(glob(os.path.join(self.data_dir, 'orientation_maps','*.png')))
#            load variance
        # self.variance_lis = sorted(glob_imgs(os.path.join(self.data_dir, 'confidence_maps')))
        self.variance_lis = sorted(glob(os.path.join(self.data_dir, 'confidence_maps','*.png')))

**Comment by egorzakharov** [comment]
Hello Carlos,

Thanks for investigating this issue! We'll take a look at it.

**Comment by carlosedubarreto** [comment]
Oh I missed one thing, on the last part of the code I wrote it wrong and Vanessa corrected me.

Instead of 
`self.variance_lis = sorted(glob(os.path.join(self.data_dir, 'confidence_maps','*.png')))`

it should be 
`self.variance_lis = sorted(glob(os.path.join(self.data_dir, 'confidence_maps','*.pny')))`
