### ISSUE TITLE
ValueError: need at least one array to stack

### ISSUE THREAD

**Issue by carlosedubarreto** [SamsungLabs/NeuralHaircut#5]
Now I'm receiving this error and now I really don know what to do.

![image](https://github.com/SamsungLabs/NeuralHaircut/assets/4061130/fb016399-c724-4b58-83d5-b9517a8e9d9b)

**Comment by BlakeXYZ** [comment]
Unrelated to your issue.. Do you have an idea where others would be interested in chatting + working through the Reconstruction Steps/troubleshooting? Some discord or slack channel?

**Comment by carlosedubarreto** [comment]
> Sorry I can't help, I haven't dug into the program yet
> 
> Unrelated to your issue.. Do you have an idea where others would be interested in chatting + working through the Reconstruction Steps/troubleshooting? Some discord or slack channel?

Sorry @BlakeXYZ , i don't know about a place like this one you said. 

I usually chat about these topics on the issues page, or when available,  thendiscussion oage of the repo.

Thats usually better fornother people to find solutions to problems they are having.

Slack or discord tand to be good to solve things in realtime but become a nightmare to reall all the messages people exchange, IMHO

**Comment by Vanessik** [comment]
I think that changing the file extension from '*.png' to '*.npy' would help (line 343)

``self.variance_lis = sorted(glob(os.path.join(self.data_dir, 'confidence_maps','*.png')))``

**Comment by carlosedubarreto** [comment]
thanks a lot @Vanessik .
I fixed on problem for me and made a new one.
You are totally right. changing that information, the code started working.
