### ISSUE TITLE
Can use own dataset? 

### ISSUE THREAD

**Issue by NaToh5** [SamsungLabs/NeuralHaircut#9]
Hi, 
I have a question about can I use my own 2D single image (Front image) ? 

Thank you.

**Comment by Vanessik** [comment]
Hi! Currently, our method works either in scenarios of multi-view data or monocular video. So, one image wouldn't be enough, but if you could capture a video of a person sitting moveless by going around him, then it would work

**Comment by NaToh5** [comment]
Thank you for your kind reply @Vanessik
